### PR TITLE
Support real layouts as children & Optimization & Refactoring & Fixes

### PR DESCRIPTION
**Pull request by gentlee**
**New**

- Add enabled prop, support transforming real layouts with Views, Fragments, Text, Images etc to placeholders. Add third example.
- Add borderRadius prop.
- Add eslint.

**Optimization & Refactoring**
- Remove usage or MaskedView for animated gradient.
- Proper usage of react hooks.

**Fix**
- Crash when children or their props are falsy

Readme updated.

... other changes

### CODE REVIEW

**Comment by juniorogaa** [comment]
Hello @chramos, can you accept this? It would be a great help 🥰

**Comment by chramos** [comment]
really appreciate!
sorry long delay I'll merge and publish a new version

**Comment by chramos** [comment]
I switched the library **@react-native-masked-view/masked-view** by the **@react-native-community/masked-view**
I'll update the installation guide on readme file

**Comment by chramos** [comment]
for some reason destructuring the react import was causing a crash.
I kept the old way to avoid the issue

**Comment by mansdahlstrom1** [comment]
> I changed the library **@react-native-masked-view/masked-view** by the **@react-native-community/masked-view** I'll update the installation guide on readme file

@chramos, can you explain why was this done?  As stated by the library author [@react-native-community/masked-view](https://www.npmjs.com/package/@react-native-community/masked-view) has been deprecated in favor of [@react-native-masked-view/masked-view](https://www.npmjs.com/package/@react-native-masked-view/masked-view)

**Pull request merged**
