### PR TITLE
fixing main module that could not be resolved

### PR DESCRIPTION
**Pull request by zgordon02**
After [this commit](https://github.com/chramos/react-native-skeleton-placeholder/commit/0285c8d70c099b9967a958ff9fba461b2d79a309), the main module in package.json needs to be updated.

### CODE REVIEW

**Comment by zgordon02** [comment]
@chramos

**Comment by aymather** [comment]
I came here for the same thing, can we please merge this asap?

**Review by Dat-Mobile — APPROVED** [review]

**Comment by Dat-Mobile** [comment]
I have to use version 5.2.0 to run it

**Comment by chramos** [comment]
oh sorry, I had not seen this PR and I fixed it by my own, sorry for that @zgordon02 
I released a new version `5.2.3`

**Pull request closed without merging**
